### ISSUE TITLE
你好，wiki 说的Socket PHP框架有了吗？

### ISSUE THREAD

**Issue by gmplato** [boiciy/ciyphp#1]
Socket PHP框架
基于Workerman的PHP Socket框架，采用端口并发机制，基本实现了无需变量锁的编程方法
选择Workerman而非效率看起来更高的swoole，Workerman完全使用php代码，易于部署，易于完善底层代码。
无需变量锁编程，和没有锁意识的编程是两回事，很多程序员无奈的发现，用户量上来了，程序不稳定了，原因在这里
建议与CiySocket框架结合使用

**Comment by boiciy** [comment]
你好。这个框架已经在游戏应用上跑了一年多。目前来看还算稳定。
目前代码还没做剥离和整理。对用户不友好。成熟后一定开源出来。

**Comment by gmplato** [comment]
好的，谢谢老师
